import { Recipe } from './types';

export const recipeDatabase: Recipe[] = [
  {
    id: "quinoa-buddha-bowl",
    title: "Mediterranean Quinoa Buddha Bowl",
    description: "A nutrient-packed bowl with protein-rich quinoa, fresh vegetables, and heart-healthy olive oil dressing",
    dietaryPreferences: ["Vegetarian", "Vegan", "Mediterranean", "Gluten-Free"],
    excludedAllergies: ["Nuts", "Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["PCOS", "Heart Problems", "Diabetes", "High Blood Pressure"],
    mealType: "Lunch",
    baseServings: 4,
    ingredients: [
      { name: "quinoa", amount: "1", unit: "cup" },
      { name: "chickpeas", amount: "1", unit: "can (15oz)" },
      { name: "cucumber", amount: "1", unit: "large" },
      { name: "cherry tomatoes", amount: "1", unit: "pint" },
      { name: "red bell pepper", amount: "1", unit: "medium" },
      { name: "red onion", amount: "1/4", unit: "cup" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "lemon juice", amount: "2", unit: "tbsp" },
      { name: "oregano", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1/2", unit: "tsp" }
    ],
    instructions: [
      "Rinse quinoa and cook according to package directions",
      "Drain and rinse chickpeas",
      "Dice cucumber, halve cherry tomatoes, and slice bell pepper",
      "Thinly slice red onion",
      "Whisk together olive oil, lemon juice, oregano, and salt",
      "Combine quinoa, chickpeas, and vegetables in a large bowl",
      "Drizzle with dressing and toss gently",
      "Let sit 10 minutes before serving to allow flavors to meld"
    ],
    healthBenefits: "High in fiber and plant protein to help regulate blood sugar and support heart health",
    prepTime: "15 min",
    cookTime: "15 min",
    nutritionalInfo: {
      calories: 320,
      protein: "12g",
      carbs: "45g",
      fat: "12g",
      fiber: "10g",
      sodium: "400mg"
    },
    storageTips: "Store in an airtight container in the refrigerator for up to 4 days. Keep dressing separate until serving to maintain freshness.",
    servingSuggestions: "Serve with a side of hummus and pita chips for a complete Mediterranean meal."
  },
  {
    id: "salmon-avocado-salad",
    title: "Omega-3 Rich Salmon & Avocado Salad",
    description: "Anti-inflammatory salmon paired with heart-healthy avocado and leafy greens",
    dietaryPreferences: ["Pescatarian", "Keto", "Low-Carb", "Gluten-Free", "Dairy-Free"],
    excludedAllergies: ["Nuts", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Heart Problems", "High Blood Pressure", "PCOS"],
    mealType: "Dinner",
    baseServings: 2,
    ingredients: [
      { name: "salmon fillets", amount: "2", unit: "pieces (6oz each)" },
      { name: "mixed greens", amount: "4", unit: "cups" },
      { name: "avocado", amount: "1", unit: "large" },
      { name: "cucumber", amount: "1/2", unit: "cup" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "lemon juice", amount: "1", unit: "tbsp" },
      { name: "garlic", amount: "1", unit: "clove" },
      { name: "dill", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1/4", unit: "tsp" },
      { name: "black pepper", amount: "1/4", unit: "tsp" }
    ],
    instructions: [
      "Season salmon with salt and pepper",
      "Heat 1 tbsp olive oil in a pan over medium-high heat",
      "Cook salmon 4-5 minutes per side until flaky",
      "Mix remaining olive oil, lemon juice, minced garlic, and dill",
      "Arrange mixed greens on plates",
      "Top with sliced avocado and diced cucumber",
      "Place cooked salmon on top",
      "Drizzle with dressing and serve immediately"
    ],
    healthBenefits: "Rich in omega-3 fatty acids to reduce inflammation and support cardiovascular health",
    prepTime: "10 min",
    cookTime: "10 min",
    nutritionalInfo: {
      calories: 450,
      protein: "35g",
      carbs: "10g",
      fat: "30g",
      fiber: "7g",
      sodium: "300mg"
    },
    storageTips: "Store cooked salmon and greens separately in airtight containers in the refrigerator for up to 2 days. Assemble before serving.",
    servingSuggestions: "Pair with a glass of sparkling water with lemon for a refreshing, low-calorie meal."
  },
  {
    id: "chia-pudding-breakfast",
    title: "Vanilla Chia Seed Breakfast Pudding",
    description: "Protein and fiber-rich breakfast pudding with natural sweetness from berries",
    dietaryPreferences: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free", "Low-Fat"],
    excludedAllergies: ["Nuts", "Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Diabetes", "PCOS", "IBS"],
    mealType: "Breakfast",
    baseServings: 2,
    ingredients: [
      { name: "chia seeds", amount: "1/4", unit: "cup" },
      { name: "almond milk", amount: "1", unit: "cup" },
      { name: "vanilla extract", amount: "1/2", unit: "tsp" },
      { name: "maple syrup", amount: "1", unit: "tbsp" },
      { name: "mixed berries", amount: "1/2", unit: "cup" },
      { name: "coconut flakes", amount: "1", unit: "tbsp" }
    ],
    instructions: [
      "Whisk chia seeds, almond milk, vanilla, and maple syrup in a bowl",
      "Let sit 5 minutes, then whisk again to prevent clumping",
      "Cover and refrigerate for at least 2 hours or overnight",
      "Stir before serving",
      "Top with mixed berries and coconut flakes",
      "Serve chilled"
    ],
    healthBenefits: "High in fiber and omega-3s to help stabilize blood sugar and support digestive health",
    prepTime: "5 min",
    cookTime: "0 min",
    nutritionalInfo: {
      calories: 200,
      protein: "6g",
      carbs: "20g",
      fat: "10g",
      fiber: "8g",
      sodium: "100mg"
    },
    storageTips: "Store in airtight containers in the refrigerator for up to 5 days. Add toppings just before serving.",
    servingSuggestions: "Enjoy with a hot cup of green tea for a balanced, energizing breakfast."
  },
  {
    id: "lentil-vegetable-curry",
    title: "Anti-Inflammatory Lentil Curry",
    description: "Warming spices and protein-rich lentils create a healing, satisfying meal",
    dietaryPreferences: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    excludedAllergies: ["Nuts", "Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Diabetes", "Heart Problems", "IBS", "Crohn's Disease"],
    mealType: "Dinner",
    baseServings: 6,
    ingredients: [
      { name: "red lentils", amount: "1", unit: "cup" },
      { name: "coconut milk", amount: "1", unit: "can (14oz)" },
      { name: "vegetable broth", amount: "2", unit: "cups" },
      { name: "onion", amount: "1", unit: "medium" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tbsp" },
      { name: "turmeric", amount: "1", unit: "tsp" },
      { name: "cumin", amount: "1", unit: "tsp" },
      { name: "carrots", amount: "2", unit: "medium" },
      { name: "spinach", amount: "2", unit: "cups" },
      { name: "coconut oil", amount: "1", unit: "tbsp" }
    ],
    instructions: [
      "Heat coconut oil in a large pot over medium heat",
      "Sauté diced onion until translucent, about 5 minutes",
      "Add minced garlic, ginger, turmeric, and cumin. Cook 1 minute",
      "Add lentils, coconut milk, and vegetable broth",
      "Bring to a boil, then reduce heat and simmer 15 minutes",
      "Add diced carrots and cook 10 more minutes",
      "Stir in spinach until wilted",
      "Season with salt and pepper to taste",
      "Serve hot over rice or quinoa"
    ],
    healthBenefits: "Anti-inflammatory spices help reduce inflammation while plant protein supports stable blood sugar",
    prepTime: "10 min",
    cookTime: "30 min",
    nutritionalInfo: {
      calories: 280,
      protein: "14g",
      carbs: "35g",
      fat: "10g",
      fiber: "12g",
      sodium: "450mg"
    },
    storageTips: "Store in an airtight container in the refrigerator for up to 5 days or freeze for up to 3 months.",
    servingSuggestions: "Serve with a side of brown rice or naan for a hearty, comforting meal."
  },
  {
    id: "greek-yogurt-parfait",
    title: "Probiotic Greek Yogurt Parfait",
    description: "Gut-healthy probiotics with antioxidant-rich berries and crunchy nuts",
    dietaryPreferences: ["Vegetarian", "Gluten-Free", "Low-Fat"],
    excludedAllergies: ["Shellfish", "Soy", "Eggs", "Wheat"],
    healthConditions: ["IBS", "Diabetes", "PCOS"],
    mealType: "Breakfast",
    baseServings: 1,
    ingredients: [
      { name: "Greek yogurt", amount: "1", unit: "cup" },
      { name: "mixed berries", amount: "1/2", unit: "cup" },
      { name: "honey", amount: "1", unit: "tbsp" },
      { name: "granola", amount: "2", unit: "tbsp" },
      { name: "chia seeds", amount: "1", unit: "tsp" }
    ],
    instructions: [
      "Layer half the yogurt in a glass or bowl",
      "Add half the berries",
      "Drizzle with half the honey",
      "Repeat layers",
      "Top with granola and chia seeds",
      "Serve immediately"
    ],
    healthBenefits: "Probiotics support digestive health while protein helps maintain stable blood sugar levels",
    prepTime: "5 min",
    cookTime: "0 min",
    nutritionalInfo: {
      calories: 250,
      protein: "15g",
      carbs: "30g",
      fat: "8g",
      fiber: "5g",
      sodium: "80mg"
    },
    storageTips: "Prepare components separately and store in the refrigerator for up to 3 days. Assemble just before serving to keep granola crunchy.",
    servingSuggestions: "Pair with a cup of herbal tea for a light, gut-friendly breakfast."
  },
  {
    id: "sweet-potato-kale-salad",
    title: "Roasted Sweet Potato & Kale Power Salad",
    description: "Nutrient-dense kale with beta-carotene rich sweet potatoes and healthy fats",
    dietaryPreferences: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    excludedAllergies: ["Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Heart Problems", "Diabetes", "PCOS", "High Blood Pressure"],
    mealType: "Lunch",
    baseServings: 4,
    ingredients: [
      { name: "sweet potatoes", amount: "2", unit: "large" },
      { name: "kale", amount: "6", unit: "cups" },
      { name: "pumpkin seeds", amount: "1/4", unit: "cup" },
      { name: "dried cranberries", amount: "2", unit: "tbsp" },
      { name: "olive oil", amount: "3", unit: "tbsp" },
      { name: "apple cider vinegar", amount: "2", unit: "tbsp" },
      { name: "Dijon mustard", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1/2", unit: "tsp" }
    ],
    instructions: [
      "Preheat oven to 400°F",
      "Cube sweet potatoes and toss with 1 tbsp olive oil and salt",
      "Roast for 25-30 minutes until tender",
      "Massage kale with a pinch of salt until softened",
      "Whisk remaining olive oil, vinegar, and mustard",
      "Combine kale, roasted sweet potatoes, pumpkin seeds, and cranberries",
      "Toss with dressing",
      "Let sit 10 minutes before serving"
    ],
    healthBenefits: "High in antioxidants and fiber to support heart health and blood sugar regulation",
    prepTime: "15 min",
    cookTime: "30 min",
    nutritionalInfo: {
      calories: 300,
      protein: "7g",
      carbs: "40g",
      fat: "14g",
      fiber: "9g",
      sodium: "350mg"
    },
    storageTips: "Store in an airtight container in the refrigerator for up to 4 days. Keep dressing separate to prevent wilting.",
    servingSuggestions: "Add grilled chicken or tofu for extra protein, and serve with a glass of iced herbal tea."
  },
  {
    id: "zucchini-noodle-pesto",
    title: "Basil Pesto Zucchini Noodles",
    description: "Low-carb spiralized zucchini with fresh basil pesto and cherry tomatoes",
    dietaryPreferences: ["Vegetarian", "Keto", "Low-Carb", "Gluten-Free"],
    excludedAllergies: ["Shellfish", "Soy", "Eggs", "Wheat"],
    healthConditions: ["Diabetes", "PCOS", "Heart Problems"],
    mealType: "Lunch",
    baseServings: 2,
    ingredients: [
      { name: "zucchini", amount: "3", unit: "large" },
      { name: "fresh basil", amount: "2", unit: "cups" },
      { name: "pine nuts", amount: "1/4", unit: "cup" },
      { name: "parmesan cheese", amount: "1/2", unit: "cup" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "olive oil", amount: "1/3", unit: "cup" },
      { name: "cherry tomatoes", amount: "1", unit: "cup" },
      { name: "salt", amount: "1/4", unit: "tsp" }
    ],
    instructions: [
      "Spiralize zucchini into noodles or use a vegetable peeler",
      "Salt zucchini noodles and let drain 10 minutes",
      "Blend basil, pine nuts, parmesan, garlic, and olive oil until smooth",
      "Pat zucchini noodles dry",
      "Toss noodles with pesto sauce",
      "Top with halved cherry tomatoes",
      "Serve immediately at room temperature"
    ],
    healthBenefits: "Low in carbohydrates while providing healthy fats to support stable blood sugar",
    prepTime: "15 min",
    cookTime: "0 min",
    nutritionalInfo: {
      calories: 350,
      protein: "10g",
      carbs: "12g",
      fat: "30g",
      fiber: "4g",
      sodium: "500mg"
    },
    storageTips: "Store zucchini noodles and pesto separately in the refrigerator for up to 3 days. Toss just before serving.",
    servingSuggestions: "Pair with grilled shrimp or chicken for a protein-packed meal."
  },
  {
    id: "turkey-stuffed-peppers",
    title: "Lean Turkey & Quinoa Stuffed Peppers",
    description: "Protein-packed bell peppers stuffed with lean turkey and nutrient-rich quinoa",
    dietaryPreferences: ["Gluten-Free", "Dairy-Free", "Low-Fat"],
    excludedAllergies: ["Nuts", "Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Heart Problems", "Diabetes", "High Blood Pressure", "PCOS"],
    mealType: "Dinner",
    baseServings: 4,
    ingredients: [
      { name: "bell peppers", amount: "4", unit: "large" },
      { name: "ground turkey", amount: "1", unit: "lb" },
      { name: "cooked quinoa", amount: "1", unit: "cup" },
      { name: "onion", amount: "1", unit: "small" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "diced tomatoes", amount: "1", unit: "can (14oz)" },
      { name: "Italian seasoning", amount: "1", unit: "tsp" },
      { name: "olive oil", amount: "1", unit: "tbsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "black pepper", amount: "1/4", unit: "tsp" }
    ],
    instructions: [
      "Preheat oven to 375°F",
      "Cut tops off peppers and remove seeds",
      "Heat olive oil in a pan, cook diced onion until soft",
      "Add garlic and cook 1 minute",
      "Add ground turkey and cook until browned",
      "Stir in quinoa, diced tomatoes, and seasonings",
      "Stuff peppers with turkey mixture",
      "Place in baking dish with 1/4 cup water",
      "Cover and bake 30-35 minutes until peppers are tender"
    ],
    healthBenefits: "Lean protein and fiber help maintain healthy weight and stable blood sugar levels",
    prepTime: "20 min",
    cookTime: "35 min",
    nutritionalInfo: {
      calories: 320,
      protein: "25g",
      carbs: "30g",
      fat: "10g",
      fiber: "7g",
      sodium: "400mg"
    },
    storageTips: "Store in an airtight container in the refrigerator for up to 4 days or freeze for up to 2 months.",
    servingSuggestions: "Serve with a side salad of mixed greens for a balanced, nutrient-rich dinner."
  },
  {
    id: "green-smoothie-bowl",
    title: "Energizing Green Smoothie Bowl",
    description: "Nutrient-dense green smoothie topped with antioxidant-rich fruits and seeds",
    dietaryPreferences: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    excludedAllergies: ["Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["PCOS", "Diabetes", "IBS"],
    mealType: "Breakfast",
    baseServings: 1,
    ingredients: [
      { name: "spinach", amount: "2", unit: "cups" },
      { name: "banana", amount: "1", unit: "medium" },
      { name: "mango", amount: "1/2", unit: "cup" },
      { name: "coconut milk", amount: "1/2", unit: "cup" },
      { name: "chia seeds", amount: "1", unit: "tbsp" },
      { name: "hemp hearts", amount: "1", unit: "tbsp" },
      { name: "blueberries", amount: "1/4", unit: "cup" },
      { name: "coconut flakes", amount: "1", unit: "tbsp" }
    ],
    instructions: [
      "Blend spinach, banana, mango, and coconut milk until smooth",
      "Pour into a bowl",
      "Top with chia seeds, hemp hearts, blueberries, and coconut flakes",
      "Serve immediately"
    ],
    healthBenefits: "Packed with antioxidants and fiber to support hormone balance and digestive health",
    prepTime: "5 min",
    cookTime: "0 min",
    nutritionalInfo: {
      calories: 280,
      protein: "6g",
      carbs: "40g",
      fat: "12g",
      fiber: "8g",
      sodium: "50mg"
    },
    storageTips: "Prepare smoothie base and store in the refrigerator for up to 24 hours. Add toppings just before serving.",
    servingSuggestions: "Top with extra fresh fruit or a sprinkle of granola for added texture."
  },
  {
    id: "baked-cod-vegetables",
    title: "Herb-Crusted Baked Cod with Vegetables",
    description: "Light, flaky fish with colorful roasted vegetables for a heart-healthy meal",
    dietaryPreferences: ["Pescatarian", "Gluten-Free", "Dairy-Free", "Low-Fat"],
    excludedAllergies: ["Nuts", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Heart Problems", "High Blood Pressure", "Kidney Disease"],
    mealType: "Dinner",
    baseServings: 4,
    ingredients: [
      { name: "cod fillets", amount: "4", unit: "pieces (6oz each)" },
      { name: "broccoli", amount: "2", unit: "cups" },
      { name: "carrots", amount: "2", unit: "medium" },
      { name: "zucchini", amount: "1", unit: "large" },
      { name: "olive oil", amount: "2", unit: "tbsp" },
      { name: "lemon juice", amount: "2", unit: "tbsp" },
      { name: "garрих1: garlic powder", amount: "1", unit: "tsp" },
      { name: "dried herbs", amount: "1", unit: "tsp" },
      { name: "salt", amount: "1/2", unit: "tsp" },
      { name: "black pepper", amount: "1/4", unit: "tsp" }
    ],
    instructions: [
      "Preheat oven to 400°F",
      "Cut vegetables into uniform pieces",
      "Toss vegetables with 1 tbsp olive oil and seasonings",
      "Arrange on one side of a baking sheet",
      "Season cod with salt, pepper, and herbs",
      "Drizzle with remaining olive oil and lemon juice",
      "Place cod on the other side of the baking sheet",
      "Bake 15-20 minutes until fish flakes easily",
      "Serve immediately"
    ],
    healthBenefits: "Low in sodium and high in omega-3s to support cardiovascular and kidney health",
    prepTime: "15 min",
    cookTime: "20 min",
    nutritionalInfo: {
      calories: 300,
      protein: "30g",
      carbs: "15g",
      fat: "12g",
      fiber: "5g",
      sodium: "250mg"
    },
    storageTips: "Store in an airtight container in the refrigerator for up to 3 days. Reheat gently to avoid overcooking fish.",
    servingSuggestions: "Serve with a side of quinoa or a light green salad for a complete meal."
  },
  {
    id: "cauliflower-rice-stir-fry",
    title: "Asian-Inspired Cauliflower Rice Stir-Fry",
    description: "Low-carb cauliflower rice with colorful vegetables and plant-based protein",
    dietaryPreferences: ["Vegetarian", "Vegan", "Keto", "Low-Carb", "Gluten-Free", "Dairy-Free"],
    excludedAllergies: ["Nuts", "Shellfish", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Diabetes", "PCOS", "Heart Problems"],
    mealType: "Dinner",
    baseServings: 4,
    ingredients: [
      { name: "cauliflower rice", amount: "4", unit: "cups" },
      { name: "bell peppers", amount: "2", unit: "medium" },
      { name: "snap peas", amount: "1", unit: "cup" },
      { name: "carrots", amount: "1", unit: "medium" },
      { name: "green onions", amount: "3", unit: "stalks" },
      { name: "garlic", amount: "3", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tbsp" },
      { name: "sesame oil", amount: "2", unit: "tbsp" },
      { name: "tamari", amount: "2", unit: "tbsp" },
      { name: "rice vinegar", amount: "1", unit: "tbsp" }
    ],
    instructions: [
      "Heat sesame oil in a large pan or wok",
      "Add minced garlic and ginger, stir-fry 30 seconds",
      "Add sliced bell peppers and carrots, cook 3 minutes",
      "Add snap peas and cook 2 minutes",
      "Add cauliflower rice and stir-fry 5 minutes",
      "Stir in tamari and rice vinegar",
      "Top with sliced green onions",
      "Serve hot"
    ],
    healthBenefits: "Very low in carbohydrates while providing fiber and antioxidants for blood sugar control",
    prepTime: "15 min",
    cookTime: "10 min",
    nutritionalInfo: {
      calories: 150,
      protein: "5g",
      carbs: "15g",
      fat: "8g",
      fiber: "6g",
      sodium: "600mg"
    },
    storageTips: "Store in an airtight container in the refrigerator for up to 4 days. Reheat in a pan for best texture.",
    servingSuggestions: "Add tofu or edamame for extra protein, and serve with a side of miso soup."
  },
  {
    id: "overnight-oats",
    title: "Fiber-Rich Overnight Oats",
    description: "Make-ahead breakfast with sustained energy from oats and healthy fats",
    dietaryPreferences: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    excludedAllergies: ["Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Diabetes", "Heart Problems", "PCOS", "IBS"],
    mealType: "Breakfast",
    baseServings: 2,
    ingredients: [
      { name: "rolled oats", amount: "1", unit: "cup" },
      { name: "almond milk", amount: "1", unit: "cup" },
      { name: "chia seeds", amount: "2", unit: "tbsp" },
      { name: "maple syrup", amount: "1", unit: "tbsp" },
      { name: "vanilla extract", amount: "1/2", unit: "tsp" },
      { name: "cinnamon", amount: "1/2", unit: "tsp" },
      { name: "apple", amount: "1", unit: "medium" },
      { name: "walnuts", amount: "2", unit: "tbsp" }
    ],
    instructions: [
      "Mix oats, almond milk, chia seeds, maple syrup, vanilla, and cinnamon",
      "Divide between two jars or containers",
      "Refrigerate overnight or at least 4 hours",
      "Top with diced apple and chopped walnuts before serving",
      "Stir and enjoy cold"
    ],
    healthBenefits: "High in soluble fiber to help lower cholesterol and stabilize blood sugar levels",
    prepTime: "5 min",
    cookTime: "0 min",
    nutritionalInfo: {
      calories: 300,
      protein: "8g",
      carbs: "45g",
      fat: "12g",
      fiber: "9g",
      sodium: "100mg"
    },
    storageTips: "Store in airtight jars in the refrigerator for up to 5 days. Add toppings just before serving.",
    servingSuggestions: "Top with a dollop of Greek yogurt for extra protein and creaminess."
  },
  {
    id: "mediterranean-hummus-wrap",
    title: "Mediterranean Hummus & Veggie Wrap",
    description: "Plant-based protein from hummus with fresh Mediterranean vegetables",
    dietaryPreferences: ["Vegetarian", "Vegan", "Mediterranean", "Dairy-Free"],
    excludedAllergies: ["Nuts", "Shellfish", "Soy", "Eggs"],
    healthConditions: ["Heart Problems", "Diabetes", "High Blood Pressure"],
    mealType: "Lunch",
    baseServings: 2,
    ingredients: [
      { name: "whole wheat tortillas", amount: "2", unit: "large" },
      { name: "hummus", amount: "1/2", unit: "cup" },
      { name: "cucumber", amount: "1", unit: "medium" },
      { name: "tomatoes", amount: "1", unit: "large" },
      { name: "red onion", amount: "1/4", unit: "small" },
      { name: "lettuce", amount: "2", unit: "cups" },
      { name: "olives", amount: "1/4", unit: "cup" },
      { name: "feta cheese", amount: "2", unit: "tbsp" },
      { name: "olive oil", amount: "1", unit: "tbsp" },
      { name: "lemon juice", amount: "1", unit: "tbsp" }
    ],
    instructions: [
      "Spread hummus evenly on tortillas",
      "Layer with lettuce, sliced cucumber, tomatoes, and red onion",
      "Add olives and crumbled feta",
      "Drizzle with olive oil and lemon juice",
      "Roll tightly and slice in half",
      "Serve immediately"
    ],
    healthBenefits: "Rich in fiber and healthy fats to support heart health and blood sugar control",
    prepTime: "10 min",
    cookTime: "0 min",
    nutritionalInfo: {
      calories: 350,
      protein: "10g",
      carbs: "45g",
      fat: "15g",
      fiber: "8g",
      sodium: "600mg"
    },
    storageTips: "Wrap tightly in foil or plastic wrap and store in the refrigerator for up to 24 hours. Best served fresh.",
    servingSuggestions: "Serve with a side of fresh fruit or a small Greek salad."
  },
  {
    id: "berry-spinach-smoothie",
    title: "Antioxidant Berry & Spinach Smoothie",
    description: "Hidden greens smoothie packed with antioxidants and natural sweetness",
    dietaryPreferences: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free", "Low-Fat"],
    excludedAllergies: ["Nuts", "Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Heart Problems", "PCOS", "Diabetes"],
    mealType: "Snack",
    baseServings: 1,
    ingredients: [
      { name: "spinach", amount: "1", unit: "cup" },
      { name: "frozen berries", amount: "1", unit: "cup" },
      { name: "banana", amount: "1/2", unit: "medium" },
      { name: "almond milk", amount: "1", unit: "cup" },
      { name: "flax seeds", amount: "1", unit: "tbsp" },
      { name: "honey", amount: "1", unit: "tsp" }
    ],
    instructions: [
      "Add all ingredients to a blender",
      "Blend until smooth and creamy",
      "Add more almond milk if needed for desired consistency",
      "Pour into a glass and serve immediately"
    ],
    healthBenefits: "High in antioxidants and fiber to reduce inflammation and support overall health",
    prepTime: "5 min",
    cookTime: "0 min",
    nutritionalInfo: {
      calories: 200,
      protein: "4g",
      carbs: "35g",
      fat: "5g",
      fiber: "7g",
      sodium: "100mg"
    },
    storageTips: "Best consumed immediately. Can be stored in a sealed container in the refrigerator for up to 24 hours; shake well before drinking.",
    servingSuggestions: "Serve with a handful of almonds for a balanced, energizing snack."
  },
  {
    id: "baked-sweet-potato",
    title: "Stuffed Sweet Potato with Black Beans",
    description: "Nutrient-dense sweet potato topped with protein-rich black beans and avocado",
    dietaryPreferences: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    excludedAllergies: ["Nuts", "Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Diabetes", "Heart Problems", "PCOS", "High Blood Pressure"],
    mealType: "Dinner",
    baseServings: 2,
    ingredients: [
      { name: "sweet potatoes", amount: "2", unit: "large" },
      { name: "black beans", amount: "1", unit: "can (15oz)" },
      { name: "avocado", amount: "1", unit: "medium" },
      { name: "lime juice", amount: "2", unit: "tbsp" },
      { name: "cilantro", amount: "1/4", unit: "cup" },
      { name: "cumin", amount: "1/2", unit: "tsp" },
      { name: "chili powder", amount: "1/2", unit: "tsp" },
      { name: "salt", amount: "1/4", unit: "tsp" }
    ],
    instructions: [
      "Preheat oven to 425°F",
      "Pierce sweet potatoes with a fork",
      "Bake 45-60 minutes until tender",
      "Warm black beans with cumin, chili powder, and salt",
      "Cut open sweet potatoes and fluff flesh",
      "Top with seasoned black beans",
      "Add diced avocado and cilantro",
      "Drizzle with lime juice and serve"
    ],
    healthBenefits: "High in fiber and complex carbohydrates to help regulate blood sugar and support heart health",
    prepTime: "10 min",
    cookTime: "60 min",
    nutritionalInfo: {
      calories: 350,
      protein: "12g",
      carbs: "55g",
      fat: "10g",
      fiber: "15g",
      sodium: "400mg"
    },
    storageTips: "Store sweet potatoes and toppings separately in the refrigerator for up to 4 days. Reheat potatoes before assembling.",
    servingSuggestions: "Serve with a side of steamed greens or a light salad for a well-rounded meal."
  },
  {
    id: "green-tea-energy-balls",
    title: "Green Tea & Almond Energy Balls",
    description: "Antioxidant-rich matcha energy bites with healthy fats and natural sweetness",
    dietaryPreferences: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    excludedAllergies: ["Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["PCOS", "Diabetes", "Heart Problems"],
    mealType: "Snack",
    baseServings: 12,
    ingredients: [
      { name: "dates", amount: "1", unit: "cup" },
      { name: "almonds", amount: "1/2", unit: "cup" },
      { name: "matcha powder", amount: "1", unit: "tbsp" },
      { name: "coconut flakes", amount: "2", unit: "tbsp" },
      { name: "vanilla extract", amount: "1/2", unit: "tsp" },
      { name: "sea salt", amount: "1/4", unit: "tsp" }
    ],
    instructions: [
      "Soak dates in warm water for 10 minutes if hard",
      "Process almonds in a food processor until finely chopped",
      "Add dates, matcha, vanilla, and salt",
      "Process until mixture holds together",
      "Roll into 12 small balls",
      "Roll in coconut flakes if desired",
      "Refrigerate 30 minutes before serving",
      "Store in refrigerator up to 1 week"
    ],
    healthBenefits: "Antioxidants from matcha help boost metabolism while healthy fats provide sustained energy",
    prepTime: "15 min",
    cookTime: "0 min",
    nutritionalInfo: {
      calories: 100,
      protein: "2g",
      carbs: "12g",
      fat: "5g",
      fiber: "2g",
      sodium: "50mg"
    },
    storageTips: "Store in an airtight container in the refrigerator for up to 7 days or freeze for up to 1 month.",
    servingSuggestions: "Enjoy with a cup of matcha tea for a midday energy boost."
  },
  {
    id: "bone-broth-soup",
    title: "Healing Bone Broth Vegetable Soup",
    description: "Gut-healing bone broth with anti-inflammatory vegetables and herbs",
    dietaryPreferences: ["Gluten-Free", "Dairy-Free", "Low-Carb"],
    excludedAllergies: ["Nuts", "Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["IBS", "Crohn's Disease", "Ulcers"],
    mealType: "Lunch",
    baseServings: 6,
    ingredients: [
      { name: "bone broth", amount: "6", unit: "cups" },
      { name: "carrots", amount: "2", unit: "medium" },
      { name: "celery", amount: "2", unit: "stalks" },
      { name: "onion", amount: "1", unit: "small" },
      { name: "garlic", amount: "2", unit: "cloves" },
      { name: "ginger", amount: "1", unit: "tsp" },
      { name: "turmeric", amount: "1/2", unit: "tsp" },
      { name: "parsley", amount: "1/4", unit: "cup" },
      { name: "sea salt", amount: "1/2", unit: "tsp" }
    ],
    instructions: [
      "Heat bone broth in a large pot",
      "Add diced carrots, celery, and onion",
      "Simmer 15 minutes until vegetables are tender",
      "Add minced garlic, ginger, and turmeric",
      "Simmer 5 more minutes",
      "Season with salt",
      "Stir in fresh parsley before serving",
      "Serve hot"
    ],
    healthBenefits: "Rich in collagen and amino acids to support gut healing and reduce inflammation",
    prepTime: "10 min",
    cookTime: "20 min",
    nutritionalInfo: {
      calories: 120,
      protein: "10g",
      carbs: "10g",
      fat: "4g",
      fiber: "3g",
      sodium: "500mg"
    },
    storageTips: "Store in an airtight container in the refrigerator for up to 5 days or freeze for up to 3 months.",
    servingSuggestions: "Serve with a slice of gluten-free bread or a small side salad for a light meal."
  },
  {
    id: "quinoa-tabbouleh",
    title: "Protein-Rich Quinoa Tabbouleh",
    description: "Mediterranean-inspired salad with complete protein quinoa and fresh herbs",
    dietaryPreferences: ["Vegetarian", "Vegan", "Mediterranean", "Gluten-Free", "Dairy-Free"],
    excludedAllergies: ["Nuts", "Shellfish", "Soy", "Eggs", "Wheat", "Dairy"],
    healthConditions: ["Heart Problems", "Diabetes", "High Blood Pressure"],
    mealType: "Lunch",
    baseServings: 4,
    ingredients: [
      { name: "quinoa", amount: "1", unit: "cup" },
      { name: "tomatoes", amount: "2", unit: "large" },
      { name: "cucumber", amount: "1", unit: "large" },
      { name: "parsley", amount: "1", unit: "cup" },
      { name: "mint", amount: "1/2", unit: "cup" },
      { name: "green onions", amount: "3", unit: "stalks" },
      { name: "olive oil", amount: "1/4", unit: "cup" },
      { name: "lemon juice", amount: "1/4", unit: "cup" },
      { name: "salt", amount: "1/2", unit: "tsp" }
    ],
    instructions: [
      "Cook quinoa according to package directions and cool",
      "Dice tomatoes and cucumber finely",
      "Chop parsley, mint, and green onions",
      "Combine quinoa with vegetables and herbs",
      "Whisk olive oil and lemon juice with salt",
      "Toss salad with dressing",
      "Let sit 30 minutes for flavors to meld",
      "Serve at room temperature"
    ],
    healthBenefits: "Complete protein and fiber help maintain stable blood sugar and support heart health",
    prepTime: "20 min",
    cookTime: "15 min",
    nutritionalInfo: {
      calories: 250,
      protein: "8g",
      carbs: "30g",
      fat: "12g",
      fiber: "6g",
      sodium: "300mg"
    },
    storageTips: "Store in an airtight container in the refrigerator for up to 5 days. Refresh with a squeeze of lemon before serving.",
    servingSuggestions: "Serve with grilled fish or falafel for a Mediterranean-inspired meal."
  }
];